#pragma once
#include <iostream>
#include <string>
#include <cstring>
#include "Socio.h"
#include "ArchivoSocios.h"
#include "ArchivoProfesor.h"
#include "ArchivoRol.h"
#include "ArchivoDisciplina.h"
#include "ArchivoPagos.h"
#include "ArchivoSalon.h" 

void menu();
void submenuSocio();
void submenuProfesor();
void submenuAdministracion();
void submenuDisciplinas();
void submenuSalon();
void submenuPagoMembresia();
void submenuMostrarSociosLista();
void submenuMostrarSociosConsulta();
void submenuMostrarSociosInforme();
void submenuMostrarProfesoresLista();
void submenuMostrarProfesoresConsulta();
void submenuMostrarProfesoresInforme();
void submenuMostrarAdministracionConsulta();
void submenuMostrarAdministracionInforme();
void submenuMostrarDisciplinasLista();
void submenuMostrarDisciplinasConsulta();
void submenuMostrarSalonConsulta();
void submenuInformesRecaudacion();

